### ISSUE TITLE
Missing sensors

### ISSUE THREAD

**Issue by piscinas** [humbertogontijo/homeassistant-roborock#16]
I have a Roborock S7 maxV and the sensors won’t be created. Only the vacuum and the camera is created. I already remove and start all over again but nothing change… I don’t see any errors on logs… is this vacuum compatible with this integration?

**Comment by calvinbui** [comment]
The integration is new, so there aren't many sensors yet. Most values are on the device entity. I see Status (charging, cleaning, etc.), battery level and fan speed on my regular S7. I assume in the future we'd get maintenance levels (filter hours) as well.

**Comment by humbertogontijo** [comment]
That's right. I rather have the sensors under the vacuum attributes than creating a lot of sensors

**Comment by Xyaren** [comment]
> That's right. I rather have the sensors under the vacuum attributes than creating a lot of sensors

Would that allow graphs though ? 
Think about the Mobile App Integration. 
Everything is a separate sensor, even if all belong to the same device.
Battery, Charging Status, temperatures, etc.

**Comment by humbertogontijo** [comment]
The attributes were added

**Comment by shred86** [comment]
Is there any concern about having too many vacuum attributes that frequently change based on this in the [HA dev docs](https://developers.home-assistant.io/docs/core/entity)?

> Entities that generate a significant amount of state changes can quickly increase the size of the database when the extra_state_attributes also change frequently. Minimize the number of extra_state_attributes for these entities by removing non-critical attributes or creating additional sensor entities.

It seems like in general, attributes are:

> Extra information to store in the state machine. It needs to be information that further explains the state, it should not be static information like firmware version.

If the goal is to align with the HA standards, I think creating separate sensors might be a better solution than attributes.

**Comment by humbertogontijo** [comment]
Absolutely. I have already started standardizing the extra attributes. The idea is to translate codes to word variables and keeping only the ones that make sense for automations

**Comment by shred86** [comment]
Nice! I’m personally good with either way, but I think the concern from the HA side is if you have an entity with a lot of extra attributes, it’s going to write all the attribute states to the database every time the vacuum state or one of its attributes changes which can increase the size of the database more than necessary. I honestly don’t think the vacuum falls into the category of “significant amount of state changes”, since this is really only happening when the vacuum is actively doing something.

I agree about not polluting the dashboard. If you do decide to go the route of creating separate sensor entities, I think two good solutions are:

1. Set the entity category of the sensor to diagnostics. This only shows up in the device page and not the dashboard. This is what the Xiaomi Miio does, but I’m not sure if these attributes really fall in the “diagnostics” category.

2. Set the default state to hidden, which also hides it from the dashboard.
