### ISSUE TITLE
Feature: Error codes as nurmerical values

### ISSUE THREAD

**Issue by Nerdiyde** [humbertogontijo/homeassistant-roborock#175]
Hey Humberto,
thanks for your awesome work. :)

I would like to use some customized error descriptions in an automation. "Unfortunately" (actually it's a very good thing for most cases) the errors are returned directly as text. 
Do you think its possible to (maybe as an attribute) also return the bare error code? This way it would be much easier to handle this in an automation.

Thanks in advance and best regards
Fab

**Comment by humbertogontijo** [comment]
I thought about removing the hard translation because it could be done using [Custom Templates](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Custom-Templates). But the Xiaomi Vacuum Map Card(which most users use along side this integration) do not translate the entities by default and have no option to use the custom templates as well (see [#543](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/543))
Anyway, I've added the error_code as attribute for the error sensor for now

**Comment by Nerdiyde** [comment]
Just saw it in the release notes. Thanks a lot for this!
Best regards from germany :)
