### ISSUE TITLE
Readme mentions problems with temporary bans, but the integration is also being submitted as core integration?

### ISSUE THREAD

**Issue by renssies** [humbertogontijo/homeassistant-roborock#219]
I've been following (but not using) this integration for a few weeks, and lately there is a lot of activity, but I'm getting a bit confused. The readme still mentions working around temporary bans, #163 mentions that there has been work done on the workarounds, but the issue is still open. 

Meanwhile the integration has been submitted to become a core integration. So does that mean the integration is now safe to use and the text in the readme is outdated?

**Comment by Lash-L** [comment]
As far as I am aware, yes it is safe to use. I have not had any problems on my side, and I have not seen anyone having issues, and everyone in the initial thread stated they their issues stopped. @humbertogontijo can confirm though.

**Comment by humbertogontijo** [comment]
The issue with bans was repeatedly connecting to Roborock mqtt, which is still possible since an integration error would reload it. But there was some code that was retrying reconnection within the integration. Now days there is no reconnection done by the integration, its all handled by paho mqtt and HA(in case of failure). That reduced reconnections from 15k a day to up to 150 a day. But I still can't tell if this is not going to ban.
BTW, there was no permanent ban, only temporary ones

**Comment by Lash-L** [comment]
Should we update the readme to reflect that @humbertogontijo ?

**Comment by straybiker** [comment]
> The issue with bans was repeatedly connecting to Roborock mqtt, which is still possible since an integration error would reload it. But there was some code that was retrying reconnection within the integration. Now days there is no reconnection done by the integration, its all handled by paho mqtt and HA(in case of failure). That reduced reconnections from 15k a day to up to 150 a day. But I still can't tell if this is not going to ban. BTW, there was no permanent ban, only temporary ones. My account never got even temporary banned

Which change did fix this?

**Comment by humbertogontijo** [comment]
@straybiker https://github.com/humbertogontijo/homeassistant-roborock/releases/tag/0.0.28

**Comment by jason-curtis** [comment]
The out of date readme note is removed in #222 .
