### ISSUE TITLE
Entity history is gone after HA restart

### ISSUE THREAD

**Issue by eugenet8k** [humbertogontijo/homeassistant-roborock#50]
Thank you for the great work! I noticed that the vacuum entity history is not persistent between HA restarts. Is it a missing feature or a bug?

Also, a side "bug", when I start cleaning from the Roborock app, the HA does not seem to demonstrate any change in the state, the vacuum just shows "Docked".

**Comment by tjafbe** [comment]
That's odd, because for me it does retain the history over restarts. Are you sure you didn't exclude the vacuum domain in the recorder configuration?

For your side question: Does that also happen right after a HA restart? Currently there is a bug that the entity stops updating after a few hours docked - see https://github.com/humbertogontijo/homeassistant-roborock/issues/41

**Comment by humbertogontijo** [comment]
I've been messing with the entity's unique_id recently. Was this restart between integration updates?

**Comment by eugenet8k** [comment]
@humbertogontijo I restart HA often because I install some things non-stop, and I noticed the history always gets reset. So it's not related to the integration update itself. I will double-check @tjafbe's suggestion with the recorder config.

**Comment by eugenet8k** [comment]
it seems not a problem anymore after recent updates. Great job!
