### ISSUE TITLE
Battery as sensor / entity

### ISSUE THREAD

**Issue by darth-aragoth** [humbertogontijo/homeassistant-roborock#612]
Is it possible to add battery level as separate entity / sensor? I can see battery level in device attributes, but I have to use a template to put it on a dashboard. Would be nice to have it as entity, as in built-in integration :)

I use Roborock S6. Thank you in advance.

**Comment by lightmaster** [comment]
I'd love to see this added as well.

**Comment by lightmaster** [comment]
It would also be nice to get a `stateName` sensor, so it says "Charging", "Washing the mop", "Segment Cleaning", etc as a history that you can look through.

**Comment by Lash-L** [comment]
Both of those are included in the core integration - I barely have time to maintain that let alone the custom as well. It is unlikely that it will come to the custom component. What is keeping you on the custom component version opposed to the core version?

**Comment by lightmaster** [comment]
Didn't realize the same person maintained both. Why still have the custom one when there is a core integration?

I initially installed the core integration, but couldn't get it to work with https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card. Pretty sure that was because the core integration doesn't create a streamable "camera" for a map like this one does. IIRC, the core has an image, but it's not a camera entity. Read the documentation for that frontend card and it linked to this repo for Roborock, so I installed this repo instead and it worked with the card right away.

**Comment by Lash-L** [comment]
> Didn't realize the same person maintained both. Why still have the custom one when there is a core integration?
> 
> I initially installed the core integration, but couldn't get it to work with [PiotrMachowski/lovelace-xiaomi-vacuum-map-card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card). Pretty sure that was because the core integration doesn't create a streamable "camera" for a map like this one does. IIRC, the core has an image, but it's not a camera entity. Read the documentation for that frontend card and it linked to this repo for Roborock, so I installed this repo instead and it worked with the card right away.

There is another dev, but I've been doing most of the dev work for a bit, he let me know a while ago his time was very limited. I converted the custom component into core and we had talked about leaving custom up for a while because there were some features that would take a bit to get to core.

The map card still doesn't work 100% with the core one due to some slow moving parts and disagreements with some core devs.

**Comment by lightmaster** [comment]
Ah, well that was the main reason I am using the custom one still. I did get around the battery and status not keeping a history by creating a template sensor helper and just mapping them to reflect the 2 attributes.

**Comment by lukasjakobi** [comment]
I will take a look at this later today and report whether i think its doable for me. I will have to look into the projects codebase first tho. 

Building on your idea I think it would be useful to check all the attributes of the vacuum and create seperate issues for all of them, that may benefit from a designated entity.
