### ISSUE TITLE
Low Priority - Update attributes when changing fan speeds, etc

### ISSUE THREAD

**Issue by jfarley248** [humbertogontijo/homeassistant-roborock#68]
First off, absolutely fantastic work on this integration, it’s awesome!

I was wondering what is a good way to update the vacuum’s attributes when changing things such as the fan/mop/mode.

For instance, I’m making a card where I have buttons for those three settings where each press cycles through each option sequentially (didn’t want to deal with drop downs or extra buttons). And each click I make I can immediately hear my vacuum chime notifying me that I changed a setting. Yet my card is relying on the integration waiting to update to see that I had just changed the fan speed, for instance. So it’ll basically look very laggy when viewing it, but we know the setting has been changed on the vacuum. 

I’m assuming it’s not a good idea to change anything with the scan interval to avoid api rate limits, so I was wondering if it’s possible for the integration to send one-off requests to update the attributes whenever there is a command that specifically changes the attributes is made?

**Comment by shred86** [comment]
It really comes down to a design choice. It is possible to update the HA device state using `self.async_update_ha_state()` immediately after a setting is changed, but there's pros and cons based on what you mentioned. I tend to like the idea of just updating the HA device state immediately, because in most cases the API calls are successful and quick, so this will make it match "reality". In the less common cases where there's a connection issue or the device rejects the command, the HA GUI will show an incorrect state for a short period (the polling time) and revert back to its previous state.

**Comment by shred86** [comment]
@humbertogontijo made a change where the vacuum properties are being requested from the Roborock server right after the mop mode or intensity is changed. This should hopefully resolve the issue you're having.

**Comment by humbertogontijo** [comment]
This is now implemented
